from minions.clients.ollama import OllamaClient
from minions.clients.groq import GroqClient
from minions.minions import Minions
from pydantic import BaseModel
import os

class StructuredLocalOutput(BaseModel):
    explanation: str
    citation: str | None
    answer: str | None

#Set up your local model, in this case we're using Llama3.2 3b via Ollama
local_client = OllamaClient(
    model_name="llama3.2",
    temperature=0.0,
    structured_output_schema=StructuredLocalOutput
)

#Set up your remote model, in this case we're using Llama3.3 70b via Groq
remote_client = GroqClient(
    model_name="llama-3.3-70b-versatile",
    api_key=os.getenv("GROQ_API_KEY")
)

# Instantiate the Minion object with the local and remote models
minions = Minions(local_client, remote_client)

#Context taken from Wikipedia about the Great Depression
context = """
The Great Depression was a severe global economic downturn from 1929 to 1939. The period was characterized by high rates of unemployment and poverty; drastic reductions in liquidity, industrial production, and trade; and widespread bank and business failures around the world. The economic contagion began in 1929 in the United States, the largest economy in the world, with the devastating Wall Street stock market crash of October 1929 often considered the beginning of the Depression. Among the countries with the most unemployed were the U.S., the United Kingdom, and Germany.

The Depression was preceded by a period of industrial growth and social development known as the "Roaring Twenties". Much of the profit generated by the boom was invested in speculation, such as on the stock market, which resulted in growing wealth inequality. Banks were subject to minimal regulation under laissez-faire economic policies, resulting in loose lending and widespread debt. By 1929, declining spending had led to reductions in manufacturing output and rising unemployment. Share values continued to rise until the Wall Street crash, after which the slide continued for three years, accompanied by a loss of confidence in the financial system. By 1933, the unemployment rate in the U.S. had risen to 25%, about one-third of farmers had lost their land, and about half of its 25,000 banks had gone out of business. The U.S. federal government under President Herbert Hoover was unwilling to intervene heavily in the economy. In the 1932 presidential election, Hoover was defeated by Franklin D. Roosevelt, who from 1933 pursued a set of expansive New Deal programs in order to provide relief and create jobs. In Germany, which depended heavily on U.S. loans, the crisis caused unemployment to rise to nearly 30% and fueled political extremism, paving the way for Adolf Hitler's Nazi Party to rise to power in 1933.

Between 1929 and 1932, worldwide gross domestic product (GDP) fell by an estimated 15%; in the U.S., the Depression resulted in a 30% contraction in GDP. Recovery varied greatly around the world. Some economies, such as the U.S., Germany and Japan started to recover by the mid-1930s; others, like France, did not return to pre-shock growth rates until later in the decade. The Depression had devastating economic effects on both wealthy and poor countries: all experienced drops in personal income, prices (deflation), tax revenues, and profits. International trade fell by more than 50%, and unemployment in some countries rose as high as 33%. Cities around the world, especially those dependent on heavy industry, were heavily affected. Construction virtually halted in many countries, and farming communities and rural areas suffered as crop prices fell by up to 60%. Faced with plummeting demand and few job alternatives, areas dependent on primary sector industries suffered the most. The outbreak of World War II in 1939 ended the Depression, as it stimulated factory production, providing jobs for women as militaries absorbed large numbers of young, unemployed men.

The precise causes for the Great Depression are disputed. One set of historians, for example, focuses on non-monetary economic causes. Among these, some regard the Wall Street crash itself as the main cause; others consider that the crash was a mere symptom of more general economic trends of the time, which had already been underway in the late 1920s. A contrasting set of views, which rose to prominence in the later part of the 20th century, ascribes a more prominent role to failures of monetary policy. According to those authors, while general economic trends can explain the emergence of the downturn, they fail to account for its severity and longevity; they argue that these were caused by the lack of an adequate response to the crises of liquidity that followed the initial economic shock of 1929 and the subsequent bank failures accompanied by a general collapse of the financial markets.

Beyond the United States
At first, the decline in the U.S. economy was the factor that triggered economic downturns in most other countries due to a decline in trade, capital movement, and global business confidence. Then, internal weaknesses or strengths in each country made conditions worse or better. For example, the U.K. economy, which experienced an economic downturn throughout most of the late 1920s, was less severely impacted by the shock of the depression than the U.S. By contrast, the German economy saw a similar decline in industrial output as that observed in the U.S. Some economic historians attribute the differences in the rates of recovery and relative severity of the economic decline to whether particular countries had been able to effectively devaluate their currencies or not. This is supported by the contrast in how the crisis progressed in, e.g., Britain, Argentina and Brazil, all of which devalued their currencies early and returned to normal patterns of growth relatively rapidly and countries which stuck to the gold standard, such as France or Belgium.

Frantic attempts by individual countries to shore up their economies through protectionist policies – such as the 1930 U.S. Smoot–Hawley Tariff Act and retaliatory tariffs in other countries – exacerbated the collapse in global trade, contributing to the depression. By 1933, the economic decline pushed world trade to one third of its level compared to four years earlier.

Economic Indicators Change (1929-1932):
| Country        | Industrial Production | Wholesale Prices | Foreign Trade | Unemployment |
|----------------|---------------------|-----------------|--------------|--------------|
| United States  | -46%                | -32%            | -70%         | +607%        |
| United Kingdom | -23%                | -33%            | -60%         | +129%        |
| France         | -24%                | -34%            | -54%         | +214%        |
| Germany        | -41%                | -29%            | -61%         | +232%        |
"""

task = "How did the combination of currency devaluation decisions and trade policies affect the economic recovery rates of Britain versus France during the Great Depression, and what does this reveal about the effectiveness of different policy responses to the crisis?"

# Execute the minions protocol for up to two communication rounds
output = minions(
    task=task,
    doc_metadata="Historical Economic Analysis",
    context=[context],
    max_rounds=2
)

#Print the final answer
print(output["final_answer"])